### ISSUE TITLE
Not practical to keep a list of allowed origins

### ISSUE THREAD

**Issue by mramirarab** [PDFTron/webviewer-cors#1]
In our application, Webviewer is hosted on a different domain than that of our portal. I'm well aware that to get Webviewer to work, I need a config file and need to whitelist our domains in configorigin.txt. However, it's virtually impossible to list all the existing domains and the domains that will/might be added in the future. I expect to have a way of whitelisting a range of URLs by allowing regex or something similar in configorigin.txt.

**Comment by mparizeau-pdftron** [comment]
This might be what you're already saying, but to clarify configorigin.txt should have the list of domains that WebViewer will be loaded in, so the domain of your portal for example.

It looks like our documentation hasn't been updated with it yet, but we do support wildcards in configorigin.txt now, so you could do something like `http://*.pdftron.com` to allow any subdomain.

Currently if you'd like to customize this more here is the code that is doing the checking https://github.com/PDFTron/webviewer-ui/blob/8.6/src/helpers/loadScript.js#L49 (Here's more info about forking the UI https://www.pdftron.com/documentation/web/guides/advanced-customization/)

If you're able to update the code to accept a generic regex we're open to accepting pull requests to get it into the official build. We'll also add this to our backlog.

**Comment by mparizeau-pdftron** [comment]
Closing now, this is no longer required for Web Component.
